### ISSUE TITLE
Inconsistent transparency in the same card.

### ISSUE THREAD

**Issue by gargomoma** [basnijholt/lovelace-ios-themes#15]
Hi!

First, thank you for the theme.
I've been using it for a few months but there's something my OCD cannot stand.

![image](https://user-images.githubusercontent.com/17122060/94839036-c07ad880-0416-11eb-83b1-a67a1baf435f.png)
![image](https://user-images.githubusercontent.com/17122060/94839332-25363300-0417-11eb-9bba-dc18d507f25b.png)

Is there a way I can fix it?

Here's one of the affected cards, in case it helps:
```
cards:
  - entity: weather.aemet
    type: weather-forecast
  - type: 'custom:fold-entity-row'
    head:
      type: section
      label: Terraza
    entities:
      - entity: sensor.mibt_temperature
        name: Temperatura Terraza
      - entity: sensor.mibt_humidity
        name: Humedad Terraza
      - entity: sensor.salon_pressure
        name: Presión Terraza
type: 'custom:vertical-stack-in-card'

```

Thanks in advance =)
