### ISSUE TITLE
Feature Request: Style the guage cards

### ISSUE THREAD

**Issue by Johmpa** [basnijholt/lovelace-ios-themes#19]
Hi!

Love the theme, just one thing stands out in my setup - the Guage colors. Is it possible to add a style option to align the colors of the guages? The blue clashes a bit with the rest of the vibrant colors. 

![image](https://user-images.githubusercontent.com/1575874/97705573-99b2cf00-1ab4-11eb-8e85-149f1c15c25e.png)

**Comment by basnijholt** [comment]
You can do something like:
```
      - entity: sensor.quarantine_meter_marcella
        max: 100
        min: 0
        name: Marcella
        severity:
          green: 95
          red: 0
          yellow: 80
        theme: Backend-selected
        type: gauge
```

Also, it doesn't look like you are using this theme... (in your screenshot)
