### ISSUE TITLE
Odd behaviour with markdown card

### ISSUE THREAD

**Issue by Hitman247m** [basnijholt/lovelace-ios-themes#30]
Hi,

I've been using your themes for a while, and everything is great. Sometimes, when refreshing the page, I end up with odd shading around the markdown cards. Here's what is looks like when it "breaks":

<img width="820" alt="broken-2021-07-27_19-46-57" src="https://user-images.githubusercontent.com/9056525/127241951-e58de590-c711-4c41-a758-bb006f8d3f1a.png">

Here is when it loads correctly:
<img width="808" alt="working-2021-07-27_19-47-23" src="https://user-images.githubusercontent.com/9056525/127241954-c4e349c4-252c-4b45-a193-54f12998503e.png">

This happens pretty randomly, and I can usually make it happen after refreshing a few times. 

Here's the config for the card:
```
type: custom:vertical-stack-in-card
cards:
  - type: markdown
    content: <h1>Switches</h1>
  - type: markdown
    content: <h2>Lights</h2>
  - type: markdown
    content: <h3>Main Floor</h3>
```

Not sure what's going on, and would appreciate some help if you've seen this before.
