### ISSUE TITLE
The views tabs at the top do not use the theme

### ISSUE THREAD

**Issue by CubeyGlyph** [basnijholt/lovelace-ios-themes#33]
Perhaps I am missing something, I'm relatively new to lovelace dashboards but it does not appear the views tabs use the theme like I see in the screenshots.  I do use kiosk mode with the following settings:
```
kiosk_mode:
  user_settings:
    - users:
        - user1
        - user2
      hide_sidebar: true
      hide_overflow: true
      ignore_entity_settings: true
```
Could that be preventing the tabs from displaying? Is there anything that can be done to make the views tabs use that view?
