### ISSUE TITLE
with that new version of HA (2022.3.0) the entry fields are no longer correct. they are now white

### ISSUE THREAD

**Issue by compujunk** [basnijholt/lovelace-ios-themes#34]
with that new version of HA (2022.3.0) the entry fields are no longer correct. they are now white
![image](https://user-images.githubusercontent.com/50024099/156482394-8f98d2c0-9401-4a16-82d7-2fa128a9a9a4.png)
![image](https://user-images.githubusercontent.com/50024099/156482614-c59c5d3a-d3ee-48dd-86d0-b3e65bcc1416.png)

**Comment by besiktas97** [comment]
Same here. Can you check and fix it please, so it will look good again ?

**Comment by basnijholt** [comment]
I'm in the middle of moving house and currently don't have HA. So no way of testing it. If someone submits a PR, I will review and merge.

**Comment by besiktas97** [comment]
I don't know how to do that so I guess this will take a long time before it can be fixed?

**Comment by basnijholt** [comment]
Please let me know whether the latest commit that I pushed works: https://github.com/basnijholt/lovelace-ios-themes/commit/bccdb96876178f521939782eece73b8c9c183095.

**Comment by besiktas97** [comment]
I just test it and it didn't work. I redownloaded the master version, restarted HA and also try the V2.5.0 with a restart. Both didn't work.

**Comment by compujunk** [comment]
nope didn't work here

**Comment by basnijholt** [comment]
Just pushed another upload. v2.6.0. Does it work now?

**Comment by besiktas97** [comment]
Nope it didn't fixed it

**Comment by groto27** [comment]
I have the same issue. It would be great if this could be fixed considering it is such a great theme.

**Comment by 2bbe** [comment]
Hi
I have made some progress with my trial and error but Im not there yet.

This gives me attached picture:
`mdc-text-field-fill-color: var(--ha-card-background)
  mdc-text-field-ink-color: var(--primary-text-color)
  mdc-select-ink-color: var(--primary-text-color)
  mdc-select-fill-color: var(--ha-card-background)
  mdc-select-label-ink-color: var(--primary-text-color)
  mdc-text-field-label-ink-color: var(--primary-text-color)
  input-fill-color: var(--ha-card-background)
  input-ink-color: var(--primary-text-color)
  input-label-ink-color: var(--primary-text-color)
  input-disabled-fill-color: var(--ha-card-background)
  input-disabled-ink-color: var(--disabled-text-color)
  input-disabled-label-ink-color: var(--disabled-text-color)
  input-idle-line-color: var(--card-background-color)
  input-dropdown-icon-color: var(--light-primary-color)
  input-hover-line-color: var(--light-primary-color)
  codemirror-property: var(--accent-color)`

any ideas?
![image](https://user-images.githubusercontent.com/40929798/157644088-129c426b-b302-436f-8f6d-23913b0a2442.png)

**Comment by basnijholt** [comment]
I just pushed another update.

There are some more alternatives that people proposed and because I don't have means to test it ATM, it would be great if someone could report which one of these look better:
```yaml
  # TODO: Below contain alternatives that have been proposed in comments
  # If anyone can test out the lines in the comments and report
  # Which one looks better, that would be great!
  mdc-text-field-fill-color: var(--card-background-color)
  # mdc-text-field-fill-color: var(--ha-card-background)
  mdc-select-fill-color: var(--card-background-color)
  # mdc-select-fill-color: var(--ha-card-background)
  input-label-ink-color: var(--secondary-text-color)
  # input-label-ink-color: var(--primary-text-color)
  input-disabled-ink-color: var(--secondary-text-color)
  # input-disabled-ink-color: var(--disabled-text-color)
  input-disabled-fill-color: var(--card-background-color)
  # input-disabled-fill-color: var(--ha-card-background)
  input-fill-color: var(--card-background-color)
  # input-fill-color: var(--ha-card-background)
  input-dropdown-icon-color: var(--primary-text-color)
  # input-dropdown-icon-color: var(--light-primary-color)
  input-idle-line-color: var(--secondary-text-color)
  # input-idle-line-color: var(--card-background-color)
  input-hover-line-color: var(--secondary-text-color)
  # input-hover-line-color: var(--light-primary-color)
```
